org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
org.gradle.offline=true
org.gradle.java.installations.paths=C:\\Program Files\\Java\\jdk-17\bin